packages:
  - packages/*
  - packages/routing-sdk/**
  - apps/*
  - apis/*
  - examples/*
  - scripts
catalog:
  "@0xsquid/widget": ^1.6.0
  "@aptos-labs/ts-sdk": 1.12.2
  "@babel/core": ^7.23.3
  "@babel/preset-env": ^7.23.3
  "@babel/preset-react": ^7.23.3
  "@binance/w3w-utils": 1.1.4
  "@binance/w3w-wagmi-connector-v2": ^1.2.3
  "@blocto/sdk": ^0.5.4
  "@changesets/cli": ^2.27.1
  "@cloudflare/workers-types": ^3.10.0
  "@cyberlab/cyber-app-sdk": v3.0.0-beta.5
  "@datadog/browser-logs": ^5.8.0
  "@datadog/browser-rum": ^5.8.0
  "@ethersproject/bignumber": ^5.7.0
  "@ethersproject/keccak256": ^5.7.0
  "@ethersproject/providers": ^5.0.0
  "@ethersproject/units": ^5.7.0
  "@gelatonetwork/limit-orders-lib": ^4.1.0
  "@gnosis.pm/safe-apps-wagmi": ^1.2.0
  "@kyberswap/pancake-liquidity-widgets": ^0.0.1-rc10
  "@layerzerolabs/scan-client": ^0.0.6
  "@material-ui/core": ^4.12.4
  "@msafe/aptos-wallet": ^3.0.6
  "@next/bundle-analyzer": 13.0.7
  "@next/eslint-plugin-next": 14.2.3
  "@orbs-network/twap-ui": 0.11.2
  "@orbs-network/twap-ui-pancake": 0.11.2
  "@popperjs/core": ^2.9.2
  "@pythnetwork/pyth-evm-js": ^1.29.2
  "@radix-ui/react-dismissable-layer": ^1.0.3
  "@radix-ui/react-slot": ^1.0.0
  "@reduxjs/toolkit": ^1.9.1
  "@snapshot-labs/snapshot.js": ^0.4.40
  "@storybook/addon-a11y": ^7.0.7
  "@storybook/addon-actions": ^7.0.7
  "@storybook/addon-essentials": ^7.0.7
  "@storybook/addon-links": ^7.0.7
  "@storybook/builder-vite": ^7.0.7
  "@storybook/react": ^7.0.7
  "@storybook/react-vite": ^7.0.7
  "@styled-system/should-forward-prop": ^5.1.5
  "@stylelint/postcss-css-in-js": ^0.37.2
  "@tanstack/react-query": ^5.52.1
  "@testing-library/react-hooks": ^8.0.1
  "@types/async-retry": ^1.4.4
  "@types/big.js": ^4.0.5
  "@types/canvas-confetti": ^1.4.2
  "@types/d3": ^7.4.0
  "@types/debug": ^4.1.7
  "@types/itty-router-extras": ^0.4.0
  "@types/js-cookie": ^3.0.2
  "@types/qs": ^6.0.0
  "@types/react": ^18.2.21
  "@types/react-datepicker": ^4.4.1
  "@types/react-dom": ^18.0.6
  "@types/react-redux": ^7.1.24
  "@types/react-router-dom": ^5.1.7
  "@types/react-transition-group": ^4.4.1
  "@types/react-window": ^1.8.8
  "@types/simplemde": ^1.11.7
  "@types/stats-lite": ^2.2.0
  "@types/styled-system": ^5.1.17
  "@types/styled-system__should-forward-prop": ^5.1.2
  "@types/use-sync-external-store": ^0.0.3
  "@types/uuid": ^8.0.0
  "@typescript-eslint/eslint-plugin": ^6.7.0
  "@typescript-eslint/parser": ^6.7.0
  "@usdv/usdv-widget": ^0.9.9
  "@vanilla-extract/css": ^1.13.0
  "@vanilla-extract/css-utils": ^0.1.3
  "@vanilla-extract/next-plugin": ^2.3.0
  "@vanilla-extract/recipes": ^0.5.0
  "@vanilla-extract/sprinkles": ^1.6.1
  "@vercel/flags": ^2.3.0
  "@vercel/toolbar": ^0.1.13
  "@vitejs/plugin-react": 4.2.1
  "@wagmi/core": 2.10.5
  "@wallchain/sdk": ^0.6.8
  "@walletconnect/ethereum-provider": ^2.14.0
  "@walletconnect/notify-client": ^1.0.0
  "@web3inbox/core": 1.2.0
  "@web3inbox/react": 1.2.0
  "@wormhole-foundation/wormhole-connect": 0.1.7
  "@yornaath/batshit": ^0.9.0
  abitype: ^0.9.8
  ajv: ^6.12.3
  aptos: 1.21.0
  async-retry: ^1.3.1
  babel-loader: ^9.1.2
  babel-plugin-styled-components: ^1.12.0
  big.js: ^5.2.2
  bottleneck: ^2.19.5
  canvas-confetti: ^1.5.1
  chart.js: ^4.4.0
  clsx: ^1.2.1
  cookies-next: ^2.1.1
  core-js: ^3.37.0
  crypto-js: ^4.2.0
  csstype: ^3.1.2
  cypress: 8.3.1
  d3: ^7.8.2
  dayjs: ^1.11.10
  debug: ^4.3.4
  decimal.js-light: ^2.5.0
  deepmerge: ^4.0.0
  easymde: 2.16.1
  eslint: ^8.32.0
  eslint-config-airbnb: ^18.2.1
  eslint-config-prettier: ^8.6.0
  eslint-plugin-address: ^0.0.2
  eslint-plugin-cypress: ^2.12.1
  eslint-plugin-import: ^2.22.1
  eslint-plugin-jsx-a11y: ^6.4.1
  eslint-plugin-lodash: ^7.4.0
  eslint-plugin-react: ^7.21.5
  eslint-plugin-react-hooks: ^4.0.0
  eventemitter3: ^4.0.7
  fast-json-stable-stringify: ^2.1.0
  framer-motion: 10.16.4
  graphql: ^16.8.1
  graphql-request: 5.0.0
  happy-dom: ^13.3.8
  husky: ^7.0.0
  itty-router: ^2.6.1
  itty-router-extras: ^0.4.2
  jest-styled-components: ^7.0.8
  jotai: ^2.4.3
  lightweight-charts: ^4.0.1
  lint-staged: ^12.3.4
  local-storage: ^2.0.0
  localforage: ^1.10.0
  lottie-react: ^2.4.0
  mnemonist: ^0.38.3
  next: 14.2.10
  next-auth: ^4.24.7
  next-seo: ^5.15.0
  next-themes: ^0.2.1
  node-fetch: ^2.6.7
  nuqs: ^1.17.4
  oauth-1.0a: ^2.2.6
  openapi-fetch: ^0.9.7
  openapi-typescript: 7.0.0-rc.0
  openapi-typescript-helpers: ^0.0.8
  polished: ^4.2.2
  postcss-scss: ^4.0.3
  postcss-syntax: ^0.36.2
  prettier: ^2.8.3
  primereact: ^10.6.6
  qrcode.react: ^3.1.0
  qs: ^6.0.0
  react: ^18.2.0
  react-chartjs-2: ^5.2.0
  react-countup: ^6.4.0
  react-datepicker: ^4.8.0
  react-dom: ^18.2.0
  react-draggable-list: 4.0.4
  react-fast-marquee: ^1.6.0
  react-images-uploading: ^3.1.7
  react-infinite-scroll-hook: ^4.1.1
  react-is: ^17.0.2
  react-jazzicon: ^1.0.4
  react-markdown: ^6.0.2
  react-popper: ^2.3.0
  react-redux: ^8.0.5
  react-router-dom: ^5.2.0
  react-window: ^1.8.7
  react-wrap-balancer: ^0.4.0
  recharts: 2.1.15
  redux-persist: ^6.0.0
  rollup-plugin-node-builtins: ^2.1.2
  serve: ^12.0.0
  siwe: ^1.1.6
  sonner: ^1.2.4
  source-map-explorer: ^2.5.2
  split-grid: ^1.0.11
  start-server-and-test: ^1.14.0
  stats-lite: ^2.2.0
  storybook: ^7.0.7
  styled-components: 6.0.7
  styled-jsx: 5.1.1
  styled-system: ^5.1.5
  stylelint: ^14.5.3
  stylelint-config-prettier: ^9.0.3
  stylelint-config-recommended: ^7.0.0
  stylelint-config-standard: ^25.0.0
  stylelint-config-styled-components: ^0.1.1
  swiper: ^11.1.12
  tilg: ^0.1.1
  tiny-warning: ^1.0.3
  toformat: ^2.0.0
  tsup: ^6.7.0
  tsx: ^4.6.1
  turbo: 2.0.6
  typescript: 5.2.2
  url-parse: ^1.5.10
  use-sync-external-store: ^1.2.0
  uuid: ^8.0.0
  viem: ^2.21.9
  vite: 5.0.12
  vite-plugin-dts: ^3.5.3
  vite-tsconfig-paths: ^4.0.3
  vitest: ^1.5.0
  wagmi: ^2.12.12
  wrangler: 2.20.2
  ws: ^8.17.1
  zod: ^3.22.3
  zustand: ^4.1.1
