packages:
  - packages/*
  - packages/routing-sdk/**
  - apps/*
  - apis/*
  - examples/*
  - scripts
catalog:
  '@0xsquid/widget': 1.6.0
  '@aptos-labs/ts-sdk': 1.12.2
  '@babel/core': 7.23.3
  '@babel/preset-env': 7.23.3
  '@babel/preset-react': 7.23.3
  '@binance/w3w-utils': 1.1.4
  '@binance/w3w-wagmi-connector-v2': 1.2.3
  '@blocto/sdk': 0.5.4
  '@changesets/cli': 2.27.1
  '@cloudflare/workers-types': 3.10.0
  '@cyberlab/cyber-app-sdk': v3.0.0-beta.5
  '@datadog/browser-logs': 5.8.0
  '@datadog/browser-rum': 5.8.0
  '@ethersproject/bignumber': 5.7.0
  '@ethersproject/keccak256': 5.7.0
  '@ethersproject/providers': 5.0.0
  '@ethersproject/units': 5.7.0
  '@gelatonetwork/limit-orders-lib': 4.1.0
  '@gnosis.pm/safe-apps-wagmi': 1.2.0
  '@kyberswap/pancake-liquidity-widgets': 0.0.1-rc10
  '@layerzerolabs/scan-client': 0.0.6
  '@material-ui/core': 4.12.4
  '@msafe/aptos-wallet': 3.0.6
  '@next/bundle-analyzer': 13.0.7
  '@next/eslint-plugin-next': 14.2.3
  '@orbs-network/twap-ui': 0.11.2
  '@orbs-network/twap-ui-pancake': 0.11.2
  '@popperjs/core': 2.9.2
  '@pythnetwork/pyth-evm-js': 1.29.2
  '@radix-ui/react-accessible-icon': 1.1.0
  '@radix-ui/react-accordion': 1.2.0
  '@radix-ui/react-alert-dialog': 1.1.1
  '@radix-ui/react-aspect-ratio': 1.1.0
  '@radix-ui/react-avatar': 1.1.0
  '@radix-ui/react-checkbox': 1.1.1
  '@radix-ui/react-collapsible': 1.1.0
  '@radix-ui/react-context-menu': 2.2.1
  '@radix-ui/react-dialog': 1.1.1
  '@radix-ui/react-dismissable-layer': 1.0.3
  '@radix-ui/react-dropdown-menu': 2.1.1
  '@radix-ui/react-hover-card': 1.1.1
  '@radix-ui/react-label': 2.1.0
  '@radix-ui/react-menubar': 1.1.1
  '@radix-ui/react-navigation-menu': 1.2.0
  '@radix-ui/react-popover': 1.1.1
  '@radix-ui/react-portal': 1.1.1
  '@radix-ui/react-progress': 1.1.0
  '@radix-ui/react-radio-group': 1.2.0
  '@radix-ui/react-scroll-area': 1.1.0
  '@radix-ui/react-select': 2.1.1
  '@radix-ui/react-separator': 1.1.0
  '@radix-ui/react-slider': 1.2.0
  '@radix-ui/react-slot': 1.1.0
  '@radix-ui/react-switch': 1.1.0
  '@radix-ui/react-tabs': 1.1.0
  '@radix-ui/react-toast': 1.2.1
  '@radix-ui/react-toggle': 1.1.0
  '@radix-ui/react-toggle-group': 1.1.0
  '@radix-ui/react-tooltip': 1.1.2
  '@reduxjs/toolkit': 1.9.1
  '@snapshot-labs/snapshot.js': 0.4.40
  '@storybook/addon-a11y': 7.0.7
  '@storybook/addon-actions': 7.0.7
  '@storybook/addon-essentials': 7.0.7
  '@storybook/addon-links': 7.0.7
  '@storybook/builder-vite': 7.0.7
  '@storybook/react': 7.0.7
  '@storybook/react-vite': 7.0.7
  '@styled-system/should-forward-prop': 5.1.5
  '@stylelint/postcss-css-in-js': 0.37.2
  '@tanstack/react-query': 5.53.3
  '@tanstack/react-query-devtools': 5.53.3
  '@tanstack/react-router': 1.52.3
  '@tanstack/router-devtools': 1.52.3
  '@testing-library/react-hooks': 8.0.1
  '@twa-dev/sdk': 7.8.0
  '@types/async-retry': 1.4.4
  '@types/big.js': 4.0.5
  '@types/canvas-confetti': 1.4.2
  '@types/d3': 7.4.0
  '@types/debug': 4.1.7
  '@types/itty-router-extras': 0.4.0
  '@types/js-cookie': 3.0.6
  '@types/lodash.range': 3.2.9
  '@types/md5': 2.3.5
  '@types/qs': 6.9.16
  '@types/react': 18.3.5
  '@types/react-datepicker': 4.4.1
  '@types/react-dom': 18.3.0
  '@types/react-redux': 7.1.24
  '@types/react-router-dom': 5.1.7
  '@types/react-transition-group': 4.4.1
  '@types/react-window': 1.8.8
  '@types/simplemde': 1.11.7
  '@types/stats-lite': 2.2.0
  '@types/styled-system': 5.1.17
  '@types/styled-system__should-forward-prop': 5.1.2
  '@types/use-sync-external-store': 0.0.3
  '@types/uuid': 8.0.0
  '@typescript-eslint/eslint-plugin': 7.18.0
  '@typescript-eslint/parser': 7.18.0
  '@uidotdev/usehooks': 2.4.1
  '@usdv/usdv-widget': 0.9.9
  '@uxuycom/web3-tg-sdk': 0.0.5
  '@vanilla-extract/css': 1.13.0
  '@vanilla-extract/css-utils': 0.1.3
  '@vanilla-extract/next-plugin': 2.3.0
  '@vanilla-extract/recipes': 0.5.0
  '@vanilla-extract/sprinkles': 1.6.1
  '@vercel/flags': 2.3.0
  '@vercel/toolbar': 0.1.13
  '@vitejs/plugin-react': 4.3.1
  '@wagmi/core': 2.10.5
  '@wallchain/sdk': 0.6.8
  '@walletconnect/ethereum-provider': 2.14.0
  '@walletconnect/notify-client': 1.0.0
  '@web3inbox/core': 1.2.0
  '@web3inbox/react': 1.2.0
  '@wormhole-foundation/wormhole-connect': 0.1.7
  '@yornaath/batshit': 0.9.0
  abitype: 0.9.8
  ajv: 6.12.3
  aptos: 1.21.0
  async-retry: 1.3.1
  autoprefixer: 10.4.20
  axios: 1.7.7
  babel-loader: 9.1.2
  babel-plugin-styled-components: 1.12.0
  big.js: 5.2.2
  bottleneck: 2.19.5
  canvas-confetti: 1.9.3
  chart.js: 4.4.0
  class-variance-authority: 0.7.0
  clsx: 2.1.1
  cmdk: 1.0.0
  codexfield-wallet-connector: 0.1.33
  cookies-next: 2.1.1
  core-js: 3.37.0
  crypto-js: 4.2.0
  csstype: 3.1.2
  cypress: 8.3.1
  d3: 7.8.2
  dayjs: 1.11.10
  debug: 4.3.4
  decimal.js-light: 2.5.0
  deepmerge: 4.0.0
  easymde: 2.16.1
  eslint: 8.57.0
  eslint-config-airbnb: 18.2.1
  eslint-config-prettier: 8.6.0
  eslint-plugin-address: 0.0.2
  eslint-plugin-cypress: 2.12.1
  eslint-plugin-import: 2.22.1
  eslint-plugin-jsx-a11y: 6.4.1
  eslint-plugin-lodash: 7.4.0
  eslint-plugin-react: 7.21.5
  eslint-plugin-react-hooks: 4.6.2
  eslint-plugin-react-refresh: 0.4.11
  eventemitter3: 4.0.7
  fast-json-stable-stringify: 2.1.0
  framer-motion: 10.16.4
  graphql: 16.8.1
  graphql-request: 5.0.0
  happy-dom: 13.3.8
  husky: 7.0.0
  is-ua-webview: 1.1.2
  itty-router: 2.6.1
  itty-router-extras: 0.4.2
  jest-styled-components: 7.0.8
  jotai: 2.4.3
  js-cookie: 3.0.5
  lightweight-charts: 4.0.1
  lint-staged: 12.3.4
  local-storage: 2.0.0
  localforage: 1.10.0
  lodash.range: 3.2.0
  lottie-react: 2.4.0
  lucide-react: 0.417.0
  md5: 2.3.0
  mnemonist: 0.38.3
  next: 14.2.10
  next-auth: 4.24.7
  next-seo: 5.15.0
  next-themes: 0.2.1
  node-fetch: 2.6.7
  nuqs: 1.17.4
  oauth-1.0a: 2.2.6
  openapi-fetch: 0.9.7
  openapi-typescript: 7.0.0-rc.0
  openapi-typescript-helpers: 0.0.8
  pino: 9.3.2
  polished: 4.2.2
  postcss: 8.4.44
  postcss-scss: 4.0.3
  postcss-syntax: 0.36.2
  prettier: 2.8.3
  primereact: 10.6.6
  qrcode.react: 3.1.0
  qs: 6.0.0
  react: 18.2.0
  react-chartjs-2: 5.2.0
  react-countup: 6.5.3
  react-datepicker: 4.8.0
  react-day-picker: 9.0.8
  react-dom: 18.2.0
  react-draggable-list: 4.0.4
  react-fast-marquee: 1.6.0
  react-ga4: 2.1.0
  react-images-uploading: 3.1.7
  react-infinite-scroll-hook: 4.1.1
  react-is: 17.0.2
  react-jazzicon: 1.0.4
  react-markdown: 6.0.2
  react-popper: 2.3.0
  react-redux: 8.0.5
  react-resizable-panels: 2.1.2
  react-responsive: 10.0.0
  react-router-dom: 5.2.0
  react-use: 17.5.1
  react-window: 1.8.7
  react-wrap-balancer: 0.4.0
  recharts: 2.1.15
  redux-persist: 6.0.0
  rollup-plugin-node-builtins: 2.1.2
  serve: 12.0.0
  siwe: 1.1.6
  sonner: 1.5.0
  source-map-explorer: 2.5.2
  split-grid: 1.0.11
  start-server-and-test: 1.14.0
  stats-lite: 2.2.0
  storybook: 7.0.7
  styled-components: 6.0.7
  styled-jsx: 5.1.1
  styled-system: 5.1.5
  stylelint: 14.5.3
  stylelint-config-prettier: 9.0.3
  stylelint-config-recommended: 7.0.0
  stylelint-config-standard: 25.0.0
  stylelint-config-styled-components: 0.1.1
  swiper: 11.1.12
  tailwind-merge: 2.5.2
  tailwindcss: 3.4.10
  tailwindcss-3d: 1.0.7
  tailwindcss-animate: 1.0.7
  tilg: 0.1.1
  tiny-warning: 1.0.3
  toformat: 2.0.0
  tsup: 6.7.0
  tsx: 4.6.1
  turbo: 2.0.6
  typescript: 5.5.4
  url-parse: 1.5.10
  use-sync-external-store: 1.2.0
  uuid: 8.0.0
  vaul: 0.9.1
  viem: 2.21.9
  vite: 5.4.2
  vite-plugin-dts: 3.5.3
  vite-plugin-node-polyfills: 0.22.0
  vite-tsconfig-paths: 4.0.3
  vitest: 1.5.0
  wagmi: 2.12.12
  wrangler: 2.20.2
  ws: 8.17.1
  zod: 3.22.3
  zustand: 4.1.1
