import { type ClassValue, clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        "text-extraSmall",
        "text-extraSmallBold",
        "text-preTitle",
        "text-small",
        "text-smallBold",
        "text-body",
        "text-bold",
        "text-h1Mobile",
        "text-h2Mobile",
        "text-h4",
        "text-h3",
      ],
    },
    theme: {
      colors: [
        "t-primary",
        "t-secondary",
        "t-fillSecondary",
        "t-third",
        "t-disabled",
        "t-placeholder",
        "t-onColor",
        "t-consistent",
        "t-inverse",
        "t-error",
        "t-buy",
        "t-sell",
        "t-link",
        "t-linkHover",
        "t-white",
        "t-emphasize",
        "border-line",
        "border-lineSubtle",
        "border-lineStrong",
        "border-new-line",
        "background-bg1",
        "background-bg2",
        "background-bg1Accent01",
        "background-bg1Accent02",
        "interactive-disabled",
        "interactive-primary",
        "interactive-primaryHover",
        "interactive-primaryActive",
        "interactive-primaryGradient",
        "interactive-primaryAccent01",
        "interactive-primaryAccent02",
        "interactive-buy",
        "interactive-buyHover",
        "interactive-buyActive",
        "interactive-sell",
        "interactive-sellHover",
        "interactive-sellActive",
        "interactive-sellGradient",
        "interactive-sellAccent01",
        "interactive-interactiveBg",
        "interactive-interactiveBgHover",
        "interactive-interactiveBgActive",
        "interactive-interactiveBgSelected",
        "interactive-interactive01",
        "interactive-interactive01Hover",
        "interactive-interactive01Active",
        "interactive-interactive01Selected",
        "interactive-interactive02",
        "interactive-interactive02Hover",
        "interactive-interactive02Active",
        "interactive-interactive02Selected",
        "interactive-interactivePopup",
        "support-success",
        "support-error",
        "support-warning",
        "support-info",
        "highLight",
        "overlay",
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return customTwMerge(clsx(inputs));
}
